[package]
name = "pyintedit"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.3"
pyo3 = {version = "0.19.0", features = ["num-bigint"]}

[lib]
crate-type = ["cdylib"]

[features]
slow = []
fast = []
default = ["slow"]
